name: ZAP Baseline Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  zap_baseline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start application
        run: |
          python main.py &
          echo "Waiting for the application to be ready..."
          for i in {1..30}; do
            if curl -s http://localhost:4000 > /dev/null; then
              echo "Application is up and running!"
              break
            else
              echo "Still waiting..."
              sleep 2
            fi
          done

      - name: Run ZAP Baseline (JSON only)
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: "http://localhost:4000"
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_action: false
          work_dir: ${{ github.workspace }}/zap_output
          cmd_options: "-J zap_report.json"

      - name: Upload ZAP JSON report
        uses: actions/upload-artifact@v4
        with:
          name: zap_report_json
          path: zap_output/zap_report.json
