name: "SOOS DAST Local Scan"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  soos:
    name: SOOS DAST Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # ou autre version selon ton projet

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start web app
        run: |
          python main.py &
          echo "Waiting for app to start..."
          for i in {1..30}; do
            if curl -s http://localhost:4000 > /dev/null; then
              echo "App is up!"
              break
            else
              echo "Waiting..."
              sleep 2
            fi
          done

      - name: Run SOOS DAST Analysis
        uses: soos-io/soos-dast-github-action@a7eb40b94c1c81eb76b178ba1befdc21823f86fa
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "mon-app-local"
          scan_mode: "baseline"
          target_url: "http://localhost:4000"
          export_format: "Sarif"
          export_file_type: "Json"

      - name: Find and rename SARIF file
        run: |
          file=$(find . -name "*.sarif.json" | head -n 1)
          if [ -n "$file" ]; then
            mv "$file" output.sarif.json
            echo "Renamed $file to output.sarif.json"
          else
            echo "No SARIF file found" && exit 1
          fi

      - name: Upload SOOS DAST SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: output.sarif.json
