name: Snyk DAST Scan

on:
  push:
    branches:
      - master

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk DAST Scan
        uses: snyk/actions/dast@master
        with:
          target-url: 'https://github.com/Tyxo50/breakableflask'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
