name: Security Scans

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  zap_baseline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start application
        run: |
          python main.py &
          echo "Waiting for the application to be ready..."
          for i in {1..30}; do
            if curl -s http://localhost:4000 > /dev/null; then
              echo "Application is up and running!"
              break
            else
              echo "Still waiting..."
              sleep 2
            fi
          done

      - name: Run ZAP Baseline (JSON output)
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: "http://localhost:4000"
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_action: false
          cmd_options: "-J dast-report.json"

      - name: Upload ZAP JSON report
        uses: actions/upload-artifact@v4
        with:
          name: dast-report
          path: dast-report.json


  snyk:
    permissions:
      contents: read 
      security-events: write 
      actions: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb

      - name: Set up env 
        uses: snyk/actions/python-3.12@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=sca-report.json 

      - name: Upload SCA report
        uses: actions/upload-artifact@v4
        with:
          name: sca-report
          path: sca-report.json

      - name: Snyk Code test
        run: snyk code test --sarif > sast-report.json || true

      - name: Upload SAST report
        uses: actions/upload-artifact@v4
        with:
          name: sast-report
          path: sast-report.json


  bandit_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit scan with JSON output
        run: bandit -r . -f json -o sast_bandit-report.json 
        continue-on-error: true 

      - name: Upload Bandit report
        uses: actions/upload-artifact@v4
        with:
          name: sast_bandit-report
          path: sast_bandit-report.json


  gitleaks_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Install Gitleaks CLI
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks
          file /usr/local/bin/gitleaks

      - name: Run Gitleaks scan (no-git mode)
        run: |
          gitleaks detect --source . --no-git --verbose --report-format json --report-path gitleaks-report.json
        continue-on-error: true

      - name: Upload Gitleaks report
        uses: actions/upload-artifact@v4
        with:
          name: secret-report
          path: gitleaks-report.json